DicentDraw/Controllers/BoxBuyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kendo.Mvc;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using DicentDraw.Models;
using DicentDraw.Models.ViewModels;
using PagedList;

namespace DicentDraw.Controllers
{
    [Authorize(Roles="User")]
    public class BoxBuyController : ProductViewController
    {
        // GET: BoxBuy
        public override ActionResult Index(int page =1)
        {
            if (Session["DessertCount"] == null)
            {
                Session["DessertCount"] = new List<AddDessertViewModel>();
            }
            IEnumerable<Gift> gift = db.Gift.Where(x => x.GiftID != "G999" && x.IsOnSales).OrderBy(x => x.GiftID);
            
            return View(gift.ToPagedList(page, 5));
        }
        public ActionResult ShowDessert()
        {
            if (Session["Gift"] == null)
            {
                return RedirectToAction("Index");
            }
            AddDessertViewModel GiftModel = Session["Gift"] as AddDessertViewModel;
            return View(GiftModel);
        }
        [HttpPost]
        public ActionResult ShowDessert(string GiftID)
        {
            var gift = db.Gift.Find(GiftID);
            var dessertCount = Session["DessertCount"] as List<AddDessertViewModel>;
            if (Session["Gift"] != null)
            {
                Session["Gift"] = null;
                dessertCount.Clear();
            }
            if (Session["Gift"] == null)
            {
                Session["Gift"] = new AddDessertViewModel()
                {
                    GiftID = gift.GiftID,
                    PieCount = gift.PieCount,
                    CookieCount = gift.CookieCount,
                    CakeCount = gift.CakeCount
                };
            }
            AddDessertViewModel GiftModel = Session["Gift"] as AddDessertViewModel;
            return View(GiftModel);
        }
        public ActionResult AddDessertCount(string id)
        {
            if (string.IsNullOrEmpty(id))
            {
                return HttpNotFound();
            }
            var NowAmount = Session["DessertCount"] as List<AddDessertViewModel>;
            int Amount = 0;
            if (NowAmount.Where(x => x.DessertID == id).Count() > 0)
            {
                Amount = NowAmount.Where(x => x.DessertID == id).FirstOrDefault().DessertAmount;
            }
            AddDessertViewModel GiftModel = Session["Gift"] as AddDessertViewModel;
            var dessert = db.Dessert.Find(id);
            AddDessertViewModel showDessert = AddModel(dessert);
            showDessert.GiftID = GiftModel.GiftID;
            showDessert.PieCount = GiftModel.PieCount;
            showDessert.CookieCount = GiftModel.CookieCount;
            showDessert.CakeCount = GiftModel.CakeCount;
            return View(showDessert);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDessertCount(AddDessertViewModel addDessert)
        {
            List<AddDessertViewModel> BuyDessert = Session["DessertCount"] as List<AddDessertViewModel>;
            int totalCookie = BuyDessert.Where(x => x.DessertKind == addDessert.DessertKind).Sum(x => x.DessertAmount);
                if (addDessert.DessertKind == "Cookie")
                {
                    if (addDessert.DessertAmount + totalCookie > addDessert.CookieCount)
                    {
                        if (addDessert.CookieCount == 0)
                        {
                            ModelState.AddModelError("DessertAmount", "此禮盒不能選餅乾");
                        }
                        else
                        {
                            ModelState.AddModelError("DessertAmount", "餅乾的數量超過" + addDessert.CookieCount + "個");
                        }
                        
                    }
                }
                if (addDessert.DessertKind == "Pie")
                {
                    if (addDessert.DessertAmount + totalCookie > addDessert.PieCount)
                    {
                        if (addDessert.PieCount == 0)
                        {
                            ModelState.AddModelError("DessertAmount", "此禮盒不能選派");
                        }
                        else
                        {
                            ModelState.AddModelError("DessertAmount", "派的數量超過" + addDessert.PieCount + "個");
                        }
                       
                    }
                }
                if (addDessert.DessertKind == "Cake")
                {
                    if (addDessert.DessertAmount + totalCookie > addDessert.CakeCount)
                    {
                        if (addDessert.CakeCount == 0)
                        {
                            ModelState.AddModelError("DessertAmount", "此禮盒不能選蛋糕");
                        }
                        else
                        {
                            ModelState.AddModelError("DessertAmount", "蛋糕的數量超過" + addDessert.CakeCount + "個");
                        }
                        
                    }
                }
            if (ModelState.IsValid)
            {
                var checkDessert = BuyDessert.Where(x => x.DessertID == addDessert.DessertID);
                if (checkDessert.Count() > 0)
                {
                    checkDessert.FirstOrDefault().DessertAmount = addDessert.DessertAmount;
                }
                else
                {
                    BuyDessert.Add(addDessert);
                }

                return RedirectToAction("ShowDessert");
            }
            var selectDessert = db.Dessert.Find(addDessert.DessertID);
            addDessert = AddModel(selectDessert);
            AddDessertViewModel GiftModel = Session["Gift"] as AddDessertViewModel;
            addDessert.GiftID = GiftModel.GiftID;
            addDessert.PieCount = GiftModel.PieCount;
            addDessert.CookieCount = GiftModel.CookieCount;
            addDessert.CakeCount = GiftModel.CakeCount;
            return View(addDessert);
        }
        public ActionResult ShowBoxDetail()
        {
            ShowTotal();
            return View();
        }
        public void ShowTotal()
        {
            var nowDessert = Session["DessertCount"] as List<AddDessertViewModel>;
            var nowGift = Session["Gift"] as AddDessertViewModel;
            List<AddDessertViewModel> allDessert = new List<AddDessertViewModel>();
            foreach (var item in nowDessert)
            {
                var dessert = db.Dessert.Find(item.DessertID);
                allDessert.Add(AddModel(dessert));
            }
            int total = allDessert.Sum(x => x.DessertPrice * x.DessertAmount);
            nowGift.GiftName = db.Gift.Find(nowGift.GiftID).GiftName;
            nowGift.GiftPrice = db.Gift.Find(nowGift.GiftID).GiftPrice;
            ViewBag.Box = nowGift.GiftName;
            ViewBag.Total = total + nowGift.GiftPrice;

        }
        [HttpPost]
        public ActionResult ShowBoxDetail(AddDessertViewModel order)
        {
            var nowDessert = Session["DessertCount"] as List<AddDessertViewModel>;
            var nowGift = Session["Gift"] as AddDessertViewModel;
            Random rad = new Random();
            string OrderID = DateTime.Now.ToString("yyyyMMddHHmmss") + rad.Next(999).ToString("000");
            if (string.IsNullOrEmpty(order.DeliveryAddress))
            {
                ModelState.AddModelError("DeliveryAddress", "請填寫送貨地址");
            }
            #region
            if (ModelState.IsValid)
            {
                db.Orders.Add(new Orders()
                {
                    Account = User.Identity.Name,
                    DeliveryAddress = order.DeliveryAddress,
                    Orderstat = 1,
                    OrderID = OrderID,
                    OrderDate = DateTime.Today.Date,
                });
                foreach (var item in nowDessert)
                {
                    string detailID = DateTime.Now.ToString("yyyyMMddHHmmss");
                    do
                    {
                        detailID = detailID + rad.Next(9999).ToString("0000");
                    } while (db.OrderDetails.Where(x => x.DetailID == detailID).Count() > 0);
                    
                    db.OrderDetails.Add(new OrderDetails()
                    {
                        DessertID = item.DessertID,
                        DetailID = detailID,
                        DessertAmount = item.DessertAmount,
                        GiftID = nowGift.GiftID,
                        OrderID = OrderID,
                    });
                    db.SaveChanges();
                }
                TempData["BuySuccess"] = "購買成功";
                Session.Clear();
                return RedirectToAction("Index");
            }
            #endregion
            ShowTotal();
            return View(order);
        }
        public ActionResult Read_BoxDetail([DataSourceRequest]DataSourceRequest Request)
        {
            var nowDessert = Session["DessertCount"] as List<AddDessertViewModel>;
            var nowGift = Session["Gift"] as AddDessertViewModel;
            List<AddDessertViewModel> allDessert = new List<AddDessertViewModel>();
            foreach (var item in nowDessert)
            {
                var dessert = db.Dessert.Find(item.DessertID);
                allDessert.Add(AddModel(dessert));
            }
            int total = allDessert.Sum(x => x.DessertPrice * x.DessertAmount);
            nowGift.GiftName = db.Gift.Find(nowGift.GiftID).GiftName;
            ViewBag.Box = nowGift.GiftName;
            ViewBag.Total = total + nowGift.GiftPrice;
            return Json(allDessert.ToDataSourceResult(Request));
        }
    }
}

DicentDraw/Views/BoxBuy/AddDessertCount.cshtml
@model DicentDraw.Models.ViewModels.AddDessertViewModel

@{
    ViewBag.Title = "增加購買數量";
}
<div class="col-md-12">
    <h4 class="text-center text-primary">請選擇數量</h4>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.DessertID)
        @Html.HiddenFor(model => model.CakeCount)
        @Html.HiddenFor(model => model.PieCount)
        @Html.HiddenFor(model => model.CookieCount)
        @Html.HiddenFor(model => model.DessertKind)
        <div class="col-md-4 col-md-offset-2">
            <img class="img-rounded" src="@Url.Content("~/images/"+ Model.DessertImage)" />
        </div>
        <div class="col-md-6">
            @Html.DisplayFor(model => model.DessertIntroduction)
        </div>
        <div class="col-md-6">
            <span class="text-primary">價格:</span><span class="text-danger">@Html.DisplayFor(model => model.DessertPrice)</span>
        </div>
        <div class="col-md-6">
            數量:@Html.EditorFor(model => model.DessertAmount, new { htmlAttributes = new { @class = "k-textbox" } })
            @Html.ValidationMessageFor(model => model.DessertAmount, "", new { @class = "text-danger" })
        </div>
        <div class="col-md-6 col-lg-offset-5">
            <button class="k-button ">確定</button>
            @Html.ActionLink("取消", "Index", null, new { @class = "k-button" })
        </div>
    }


</div>

DicentDraw/Views/BoxBuy/Index.cshtml
@model IPagedList<DicentDraw.Models.Gift>
@{
    ViewBag.Title = "選擇禮盒";
    int i = 0;
}
@section Styles{
<link href="~/Content/PagedList.css" rel="stylesheet" />
}
<div class="col-md-12">
    <h2 class="text-center">請選擇禮盒</h2>
    @using (Html.BeginForm("ShowDessert","BoxBuy"))
    {
        <table>

            @foreach (var item in Model)
            {
                <tr>
                    @if (i == 0)
                    {
                        <td style="text-align:center">
                          <label for="@item.GiftID"><img class="img-rounded" src="@Url.Content("~/images/"+item.GiftImage)" /></label>  
                           <p><input type="radio" name="GiftID" id="@item.GiftID" value="@item.GiftID" checked />@item.GiftName</p>
                        </td>

                        i++;
                    }
                    else
                    {
                        <td style="text-align:center">
                            <label for="@item.GiftID"><img class="img-rounded" src="@Url.Content("~/images/"+item.GiftImage)" /></label>
                            <p><input type="radio" name="GiftID" id="@item.GiftID" value="@item.GiftID" />@item.GiftName</p>
                        </td>
                    }
                </tr>
            }
        </table>
    <div class="pager">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
        <div class="col-md-12 col-lg-offset-5">
            <input type="submit" class="k-button" value="選擇禮盒" />
        </div>
    }


</div>

DicentDraw/Views/BoxBuy/ShowBoxDetail.cshtml
@model DicentDraw.Models.ViewModels.AddDessertViewModel

@{
    ViewBag.Title = "購買明細";
}
@section Scripts{
    <script>
        function OnRemove(e) {
            location.reload();
        }
    </script>
}
<h2 class="col-lg-12 text-success">購買明細</h2>
<h3 class="col-md-12 text-center">使用禮盒: @ViewBag.Box</h3>
<div class="col-md-12">
    @(Html.Kendo()
.Grid<DicentDraw.Models.ViewModels.AddDessertViewModel>()
.Name("DessertDetail")
    .Columns(columns =>
    {
        columns.Bound(x => x.DessertName).Title("點心名稱");
        columns.Bound(x => x.DessertPrice).Title("單價");
        columns.Bound(x => x.DessertAmount).Title("數量");
        columns.Template(x => x.DessertPrice * x.DessertAmount).Title("小計").ClientTemplate("#:DessertPrice*DessertAmount#")
         .FooterTemplate("總共:" + ViewBag.Total + "元(加上禮盒價格)");
    })
                    .Pageable()
                    .DataSource(datasource =>
                                                datasource
                                                .Ajax()
                                                .Model(model => model.Id(d => d.DessertID))
                                                                .Read("Read_BoxDetail", "BoxBuy")
                                                .PageSize(5)
                                                                )))
    <h3 class="text-danger">若確認購買請填寫送貨地點</h3>
    @using (Html.BeginForm())
    {
        <h4>@Html.DisplayNameFor(Model => Model.DeliveryAddress)</h4>
        @Html.EditorFor(Model => Model.DeliveryAddress, new { htmlAttributes = new { @class = "k-textbox" } })
        @Html.ValidationMessageFor(Model => Model.DeliveryAddress, "", new { @class = "text-danger" })
        <p><input type="submit" value="確定" class="k-button" style="height:30px;" />@Html.ActionLink("取消購買", "Cancel", null, new { @class = "k-button", style = "height:30px;" })</p>

    }
</div>

DicentDraw/Views/BoxBuy/ShowDessert.cshtml
@model DicentDraw.Models.ViewModels.AddDessertViewModel
@{
    ViewBag.Title = "商品購買";
}

@section Styles{
    <style>
        div.k-tabstrip {
            background: none transparent;
            border-width: 0;
        }

            div.k-tabstrip .k-tabstrip-items {
                padding: 0;
            }

            div.k-tabstrip .k-content {
                margin: 0;
            }
    </style>
}
@section Scripts{
    <script>
        @if (TempData["BuySuccess"] != null)
        {
            @:alert("@TempData["BuySuccess"]")
                                        }
    </script>
}
<script type="text/x-kendo-tmpl" id="template">
    <div class="col-lg-5" style="height:450px">
        <div class="col-lg-offset-3"><img src="@Url.Content("~/images/")#:DessertImage#" class="img-thumbnail" alt="#:DessertName#" /></div>
        <h3 class="text-primary">#:DessertName#</h3>
        <h3><span class="text-danger">目前訂購數量:</span>#:DessertAmount#</h3>
        <a href="@Url.Action("AddDessertCount")/#:DessertID#" class="k-button">選擇數量</a>
        <p style="color:blue;font-family:'微軟正黑體' sans-serif;">#:DessertIntroduction#</p>
    </div>
</script>

@Html.AntiForgeryToken()
@Html.HiddenFor(model => model.GiftID)
<div class="col-md-12 text-center">
    <h2>你現在可以選擇的</h2>
    @if (Model.CookieCount != 0)
    {
        <h3>餅乾總數量為: @Model.CookieCount 個</h3>
    }
 
    @if (Model.PieCount != 0)
    {
        <h3>派總數量為: @Model.PieCount 個</h3>
    }
    @if (Model.CakeCount != 0)
    {
        <h3>蛋糕總數量為: @Model.CakeCount 個</h3>
    }

</div>
<div class="col-md-12">
    @(Html.Kendo()
    .TabStrip()
    .Name("DessertShow").
            Items(tabstrip =>
    {
        tabstrip.Add()
            .Selected(true)
            .Text("餅乾").Content(@<div>
                @(Html
                .Kendo()
                .ListView<DicentDraw.Models.ViewModels.AddDessertViewModel>()
                .Name("Dessert")
                .TagName("div")
                .ClientTemplateId("template")
                .DataSource(dataSource =>
                {
                    dataSource.Read(read => read.Action("Cookie_Read", "DessertBuy"));
                    dataSource.PageSize(10);
                })
            .Pageable())
            </div>);
        tabstrip.Add()
            .Text("蛋糕")
            .Content(@<div>
                @(Html
                .Kendo()
                .ListView<DicentDraw.Models.ViewModels.AddDessertViewModel>()
                .Name("Dessert2")
                .TagName("Div")
                .ClientTemplateId("template")
                .DataSource(dataSource =>
                {
                    dataSource.Read(read => read.Action("Cake_Read", "DessertBuy"));
                    dataSource.PageSize(10);

                })
                 .Pageable())
            </div>);
        tabstrip.Add()
            .Text("派")
            .Content(@<div>
                @(Html
                .Kendo()
                .ListView<DicentDraw.Models.ViewModels.AddDessertViewModel>()
                .Name("Dessert3")
                .TagName("Div")
                .ClientTemplateId("template")
                .DataSource(dataSource =>
                {
                    dataSource.Read(read => read.Action("Pie_Read", "DessertBuy"));
                    dataSource.PageSize(10);

                })
                 .Pageable())
            </div>);
    }))
</div>
<div class="col-md-12 col-md-offset-4">
    @Html.ActionLink("確認訂購明細", "ShowBoxDetail", null, new { @class = "k-button", style = "width:300px;Heigh:100px;font-size:32px" })
</div>